language: go
go:
  - tip
  - 1.7
  - 1.6

sudo: false

before_install:
  - go get -u github.com/golang/lint/golint
  - mkdir -p $GOPATH/src/github.com/vbatts && ln -sf $(pwd) $GOPATH/src/github.com/vbatts/git-validation && go get ./...

install: true

script:
  - go vet -x ./...
  - golint ./...
  - go build .
  - go test -v ./...

